flaskBlog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    content = TextAreaField('Content',validators=[DataRequired()])
    submit = SubmitField('Post')

flaskBlog/main/routes.py
from flask import render_template, request, Blueprint, jsonify
from flaskBlog.models import Post



main = Blueprint('main',__name__)


@main.route("/")
@main.route("/home")
def home():
    page_no = request.args.get('page',1,type=int)
    posts= Post.query.order_by(Post.date_posted.desc()).paginate(page=page_no,per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')


@main.route("/api",methods=['GET'])
def api():
    result=[]
    if 'name' in request.args:
        result.append( {'text':'Hello' + str(request.args['name'])})
    else:
        result.append({'text':'Hello World!'})
    return jsonify(result)
       

flaskBlog/posts/routes.py
from flask import render_template,flash,redirect,url_for,request,abort, Blueprint
from flask_login import current_user, login_required
from flaskBlog import db
from flaskBlog.models import Post
from flaskBlog.posts.forms import PostForm



posts = Blueprint('posts',__name__)



@posts.route("/post/new",methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit() :
        post = Post(title=form.title.data,content=form.content.data,author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your Post has been created','success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='New Post',form=form,legend='New Post')

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html',title=post.title,post=post)

@posts.route("/post/<int:post_id>/update",methods=['GET','POST'])
@login_required
def update_post(post_id):
    form = PostForm()
    post = Post.query.get_or_404(post_id)
    if current_user.id != post.author.id :
        abort(403)
    
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated','success')
        return redirect(url_for('posts.post',post_id=post.id))

    elif request.method == 'GET':
        form.content.data = post.content
        form.title.data = post.title

    return render_template('create_post.html',title='Update Post',legend='Update Post',form=form)


@posts.route("/post/<int:post_id>/delete",methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user.id != post.author.id :
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your Post has been deleted','success')
    return redirect(url_for('main.home'))
    

flaskBlog/users/routes.py
from flask import render_template,flash,redirect,url_for,request, Blueprint
from flaskBlog import db, bcrpyt
from flaskBlog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPassword
from flaskBlog.models import User,Post
from flask_login import login_user,current_user,logout_user,login_required
from flaskBlog.users.utils import save_picture, send_reset_email



users = Blueprint('users',__name__)

@users.route("/register" , methods=['GET','POST'])
def register():
    if current_user.is_authenticated :
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrpyt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username= form.username.data , email=form.email.data , password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account successfully created You can now login', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html',form=form)

@users.route("/login", methods=['GET','POST'])
def login():
    if current_user.is_authenticated :
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrpyt.check_password_hash(user.password,form.password.data):
            login_user(user, form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'Check Username and password ','danger')
    return render_template('login.html',form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))



@users.route("/account",methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_fn = save_picture(form.picture.data)
            current_user.image_file= picture_fn
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account updated Successfully','success')
    elif request.method=='GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static',filename='profile_pics/'+ current_user.image_file)
    return render_template('account.html',title='Account',image_file=image_file, form=form)




@users.route("/user/<string:username>")
def user_posts(username):
    page_no = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts= Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page_no,per_page=5)
    image_file = url_for('static',filename='profile_pics/'+ user.image_file)
    return render_template('user_posts.html', posts=posts,user=user,image_file=image_file)



@users.route("/reset_password",methods=['GET','POST'])
def reset_password():
    if current_user.is_authenticated :
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Am email with instructions has been sent to your email.Please check','info')
        return redirect(url_for('users.login'))

    return render_template('reset_request.html',title='Reset Password',form=form)

@users.route("/reset_password/<string:token>",methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated :
        return redirect(url_for('main.home'))

    user = User.verify_reset_token(token)
    if user is None:
        flash('The token is invalid or expired','warning')
        return redirect(url_for('users.reset_password'))
    form = ResetPassword()
    if form.validate_on_submit():
        hashed_password = bcrpyt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your Password has been changed. You can now login', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',title='Reset password',form=form)

flaskBlog/templates/about.html
{% extends 'layout.html' %}

{% block content %}
<h1>About Page</h1>
<p style="white-space: pre-line;">
    This site is built by Ratan Narayan Hegde, Computer Science undergrad in RV College of Engineering. 
    You can contact me on my mail- ratanhegde08@gmail.com 
    Checkout the code for the project  <a href="https://github.com/RatanNarayanHegde/Flask-Blog" style="color:dodgerblue">GitHub Repo</a>
</p>

{% endblock %}

flaskBlog/templates/account.html
{% extends 'layout.html' %}

{% block content %}
<div class="border text-center mt-4">
    <div class="account-info mt-2">
        <div>
            <img src="{{ image_file }}" alt="" class="img-thumbnail rounded-circle">
        </div>
        <div class="d-flex flex-column justify-content-center">
            <h1>{{ current_user.username }}</h1>
            <p>{{ current_user.email }}</p>
        </div>
    </div>
   
    <a class="btn btn-primary btn-sm" href="{{ url_for('users.user_posts',username=current_user.username) }}" role="button">My Posts </a>
    <div class="container w-50 mt-4">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <legend class="border-bottom mb-4 mt-2">Account Info</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>



</div>


{% endblock %}

flaskBlog/templates/create_post.html
{% extends 'layout.html' %}

{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <legend class="border-bottom mb-4 mt-2">{{ legend }}</legend>
    <div class="form-group">
        {{ form.title.label(class="form-control-label") }}
        {% if form.title.errors %}
        {{ form.title(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.title.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.title(class="form-control form-control-lg") }}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.content.label(class="form-control-label") }}
        {% if form.content.errors %}
        {{ form.content(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.content.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.content(class="form-control form-control-lg") }}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
</form>

{% endblock %}

flaskBlog/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    {% for post in posts.items %}
        <div class="article border">
            <div class="post-metadata">
                <img class="rounded-circle mt-1 ml-1" src="{{ url_for('static',filename='profile_pics/'+post.author.image_file) }}" alt="" id="post_img">
                <span class="Postauthor ml-2"><a href="{{ url_for('users.user_posts',username=post.author.username) }}">{{ post.author.username }}</a></span>
                <span class="Postdate mr-1"> {{ post.date_posted.strftime('%d %b,%Y') }}</span>
            </div>
            <h3 class="mt-2 ml-2 mr-2"><a href="{{ url_for('posts.post',post_id=post.id) }}">{{ post.title }}</a></h3>
            <p class="ml-2">{{ post.content }}</p>
            
        </div>
    {% endfor %}

    <nav aria-label="Page navigation example" class="mt-2 d-flex justify-content-center">
        <ul class="pagination pagination-sm">
          {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=1) %}
            {% if page_num %}
                {% if page_num == posts.page %}
                    <li class="page-item active"><a class="page-link" href="{{ url_for('main.home',page=page_num )}}">{{ page_num }} <span class="sr-only">(current)</span> </a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="{{ url_for('main.home',page=page_num )}}">{{ page_num }}</a></li>
                {% endif %}
            {% else %}
            <li class="page-item">...</li>
            {% endif %}
          {% endfor %}
        </ul>
      </nav>
{% endblock %}

flaskBlog/templates/layout.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static',filename='main.css') }}">
    {% if title %}
    <title> StoryBook-{{ title }}</title>
    {% else %}
    <title> StoryBook</title>
    {% endif %}
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">StoryBook</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.account') }}">My Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>

    </nav>


    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category,message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-4">
                <div class="border">
                    <h1>Side Note</h1>
                    <ul class="list-group">
                        <li class="list-group-item">Log in or register to post</li>
                        <li class="list-group-item">Update your profile picture in 'my account'</li>
                        <li class="list-group-item">You can view posts specific to the user by clicking the username</li>
                        <li class="list-group-item">Comment feature on Posts coming soon ...</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>

flaskBlog/templates/login.html
{% extends 'layout.html' %}

{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <legend class="border-bottom mb-4 mt-2">Log in</legend>
    <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
        {{ form.email(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.email(class="form-control form-control-lg") }}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {% if form.password.errors %}
        {{ form.password(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.password(class="form-control form-control-lg") }}
        {% endif %}
    </div>
    <div class="form-check">
        {{ form.remember(class="form-check-input") }}
        {{ form.remember.label(class="form-check-label") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
    <small class="text-muted ml-2">
        <a href="{{ url_for('users.reset_password') }}">Forgot Password?</a>
    </small>
</form>
<div class="border-top pt-3">
    <small class="text-muted">
        Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
    </small>
</div>
{% endblock %}

flaskBlog/templates/post.html
{% extends 'layout.html' %}

{% block content %}

<div class="article border">
    <div class="post-metadata">
        <img class="rounded-circle mt-1 ml-1"
            src="{{ url_for('static',filename='profile_pics/'+post.author.image_file) }}" alt="" id="post_img">
        <span class="Postauthor ml-2"><a href="{{ url_for('users.user_posts',username=post.author.username) }}">{{ post.author.username }}</a></span>
        <span class="Postdate mr-1"> {{ post.date_posted.strftime('%d %b,%Y') }}</span>
        {% if post.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm ml-1 mt-1" href="{{ url_for('posts.update_post',post_id=post.id) }}">Update</a>
                <button class="btn btn-danger btn-sm mt-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
        {% endif %}
        
    </div>
    <h3 class="mt-2 ml-2 mr-2">{{ post.title }}</h3>
    <p class="ml-2" id="article-content" style="white-space: pre-line;">{{ post.content }}</p>

</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this post?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post',post_id=post.id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

flaskBlog/templates/register.html
{% extends 'layout.html' %}

{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <legend class="border-bottom mb-4 mt-2">Join Today</legend>
    <div class="form-group">
        {{ form.username.label(class="form-control-label") }}
        {% if form.username.errors %}
        {{ form.username(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.username(class="form-control form-control-lg") }}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
        {{ form.email(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.email(class="form-control form-control-lg") }}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {% if form.password.errors %}
        {{ form.password(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.password(class="form-control form-control-lg") }}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.confirmPassword.label(class="form-control-label") }}
        {% if form.confirmPassword.errors %}
        {{ form.confirmPassword(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.confirmPassword.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.confirmPassword(class="form-control form-control-lg") }}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
</form>
<div class="border-top pt-3">
    <small class="text-muted">
        Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
    </small>
</div>
{% endblock %}

flaskBlog/templates/reset_request.html
{% extends 'layout.html' %}

{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <legend class="border-bottom mb-4 mt-2">Reset Password</legend>
    <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
        {{ form.email(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.email(class="form-control form-control-lg") }}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
</form>
{% endblock %}

flaskBlog/templates/reset_token.html
{% extends 'layout.html' %}

{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <legend class="border-bottom mb-4 mt-2">Reset Password</legend>
    <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {% if form.password.errors %}
        {{ form.password(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.password(class="form-control form-control-lg") }}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.confirmPassword.label(class="form-control-label") }}
        {% if form.confirmPassword.errors %}
        {{ form.confirmPassword(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.confirmPassword.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.confirmPassword(class="form-control form-control-lg") }}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
</form>
{% endblock %}

flaskBlog/templates/user_posts.html
{% extends 'layout.html' %}

{% block content %}
    <div class="account-info mt-2">
        <div>
            <img src="{{ image_file }}" alt="" class="img-thumbnail rounded-circle">
        </div>
        <div class="d-flex flex-column justify-content-center">
            <h1>{{ user.username }}</h1>
            <p>{{ user.email }}</p>
        </div>
    </div>
    <h2 class="mt-2 pl-4"> Total Posts - {{ posts.total }} </h2>
    {% for post in posts.items %}
        <div class="article border">
            <div class="post-metadata">
                <img class="rounded-circle mt-1 ml-1" src="{{ url_for('static',filename='profile_pics/'+post.author.image_file) }}" alt="" id="post_img">
                <span class="Postauthor ml-2"><a href="#">{{ post.author.username }}</a></span>
                <span class="Postdate mr-1"> {{ post.date_posted.strftime('%d %b,%Y') }}</span>
            </div>
            <h3 class="mt-2 ml-2 mr-2"><a href="{{ url_for('posts.post',post_id=post.id) }}">{{ post.title }}</a></h3>
            <p class="ml-2">{{ post.content }}</p>
            
        </div>
    {% endfor %}

    <nav aria-label="Page navigation example" class="mt-2">
        <ul class="pagination pagination-sm">
          {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=1) %}
            {% if page_num %}
                {% if page_num == posts.page %}
                    <li class="page-item active"><a class="page-link" href="{{ url_for('users.user_posts',username=user.username,page=page_num )}}">{{ page_num }} <span class="sr-only">(current)</span> </a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts',username=user.username,page=page_num )}}">{{ page_num }}</a></li>
                {% endif %}
            {% else %}
            <li class="page-item">...</li>
            {% endif %}
          {% endfor %}
        </ul>
      </nav>
{% endblock %}